[package]
name = "test-keishis"
version = "0.2.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "test_keishis"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.27.0"
