# See https://domluna.github.io/JuliaFormatter.jl/stable/ for a list of options
indent = 4
whitespace_typedefs = false
whitespace_ops_in_indices = true
remove_extra_newlines = true
always_use_return = true
whitespace_in_kwargs = false
format_docstrings = true
normalize_line_endings = "unix"
indent_submodule = true
separate_kwargs_with_semicolon = true
