[[rs-twwl]]
arch = "x86_64"
git-tree-sha1 = "a81dc99b45c24c85743cb70ab3977d3447f8fc70"
libc = "glibc"
os = "linux"

    [[rs-twwl.download]]
    sha256 = "8f504bad6ef99e8717f538955104970727a3b1084958f093c57b3a40b54d2dd4"
    url = "https://github.com/KeishiS/test-keishis/releases/download/rust-v0.2.5/target-linux-x86_64.tar.gz"
[[rs-twwl]]
arch = "aarch64"
git-tree-sha1 = "1df5ce8ae221c9a6218dc29e104abe99e3afc27b"
libc = "glibc"
os = "linux"

    [[rs-twwl.download]]
    sha256 = "d6d6482eed5b0ce3ad0ff8b4fe00662259aba586ddc133ba2c96f8d870884d58"
    url = "https://github.com/KeishiS/test-keishis/releases/download/rust-v0.2.5/target-linux-aarch64.tar.gz"
[[rs-twwl]]
arch = "x86_64"
git-tree-sha1 = "c9c39ccaa4331a487df7d9f9ec6698300f034668"
os = "macos"

    [[rs-twwl.download]]
    sha256 = "c1f3931b0967442a5334e046c0a659f52656a021e6c5aa6b577245450157f811"
    url = "https://github.com/KeishiS/test-keishis/releases/download/rust-v0.2.5/target-macos-x86_64.tar.gz"
[[rs-twwl]]
arch = "aarch64"
git-tree-sha1 = "35b21f5a2d4ef0c8d33cf3637947a39f50200f47"
os = "macos"

    [[rs-twwl.download]]
    sha256 = "35718bc54f41ea0dd97a0271e401951f9182619637aa03591bab3e6198951f85"
    url = "https://github.com/KeishiS/test-keishis/releases/download/rust-v0.2.5/target-macos-aarch64.tar.gz"
[[rs-twwl]]
arch = "x86_64"
git-tree-sha1 = "f96bbdf29676d48584b01158c0a47af7c50ce40f"
os = "windows"

    [[rs-twwl.download]]
    sha256 = "45ac41b1af66540e8c96ffe2d81e221e1b4d3f22b5571c2e372b00465ec8a67e"
    url = "https://github.com/KeishiS/test-keishis/releases/download/rust-v0.2.5/target-windows-x86_64.tar.gz"
[[rs-twwl]]
arch = "aarch64"
git-tree-sha1 = "f08ab1b39c87ae282fa1ffa91477e73f211e848e"
os = "windows"

    [[rs-twwl.download]]
    sha256 = "32dc3e2b140bf75c15c8a2021db018e0d2276dfb6ca9908c82a0c60fcfed659d"
    url = "https://github.com/KeishiS/test-keishis/releases/download/rust-v0.2.5/target-windows-aarch64.tar.gz"
